### ISSUE TITLE
[Question] Light Theme 浅色主题

### ISSUE THREAD

**Issue by wopanda** [yan42685/obsidian-clever-search#17]
似乎只有暗色背景的默认设置。

**Comment by yan42685** [comment]
嗯，临时方案是通过 `style settings` 插件自定义颜色。我近期空闲时间很少，以后再更新浅色主题。

**Comment by Moyf** [comment]
想提 FR 的时候看到这个 issue，分享一下自用的一个亮色 CSS：

```css

/* 亮色模式的 Clever Search 外观 */
.theme-light .cs-modal, 
.theme-light .cs-floating-window-container {
    background-color: #FFF;
}

.theme-light .svelte-1k7yxfd {
    background-color: unset !important;
}

.theme-light .svelte-1k7yxfd.selected  {
    /* background-color: var(--color-accent) !important; */
    background-color: #474747 !important;
    color: white !important;
}

.theme-light .right-pane.svelte-1k7yxfd.svelte-1k7yxfd.svelte-1k7yxfd,
.theme-light .search-bar.svelte-1k7yxfd input.svelte-1k7yxfd.svelte-1k7yxfd {
    background-color: unset !important;
}

.theme-light .right-pane.svelte-1k7yxfd .preview-container ul button.file-sub-item.svelte-1k7yxfd.svelte-1k7yxfd {
    background-color: unset;
}

.theme-light .result-items.svelte-1k7yxfd ul.svelte-1k7yxfd button.svelte-1k7yxfd:hover, 
.theme-light .result-items.svelte-1k7yxfd ul.svelte-1k7yxfd button.selected.svelte-1k7yxfd,
.theme-light .right-pane.svelte-1k7yxfd .preview-container ul button.file-sub-item.selected.svelte-1k7yxfd.svelte-1k7yxfd {
    /* background-color: var(--background-primary) !important; */
}

:is(.theme-dark.pt-accent-style-borderandfilled-dt, .theme-light.pt-accent-style-borderandfilled-lt) :is(.pcr-button, .modal button:not(.mod-cta):not(.mod-warning), .graph-control-content button, .modal-setting-nav-bar .clickable-icon, .document-search-button, .pdf-toolbar-button):hover {
    color: unset !important;
    /* background-color: var(--background-primary) !important; */
}

```


不知道怎么用的话可以参考：[如何在OB内应用CSS修改](https://forum-zh.obsidian.md/t/topic/43995)](https://forum-zh.obsidian.md/t/topic/43995)
